# Generated by Django 5.1.6 on 2025-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='recommended',
            field=models.CharField(default='recommended', max_length=255),
        ),
    ]
