# Generated by Django 5.1.6 on 2025-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_allowance_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='type',
            field=models.CharField(default='type', max_length=255),
        ),
    ]
