# Generated by Django 5.1.6 on 2025-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allowance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='networth',
            field=models.CharField(default='networth', max_length=255),
        ),
    ]
