# Generated by Django 5.1.6 on 2025-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_allowance_networth'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='monthlyspent',
            field=models.CharField(default='month', max_length=255),
        ),
    ]
