# Generated by Django 5.1.6 on 2025-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_allowance_monthlyspent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='monthlyspent',
            field=models.IntegerField(),
        ),
    ]
