# Generated by Django 5.1.6 on 2025-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_allowance_monthlyspent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='monthlyspent',
            field=models.CharField(default='month', max_length=255),
        ),
    ]
